In [ ]:
#interger encoding

#give number to all vocabolary in text and then convert sentence to number vector
#do padding for same size

In [ ]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [ ]:
from keras.preprocessing.text import Tokenizer #it is for converting word to small letters and generate indices
tokenizer = Tokenizer(oov_token='<nothing>') #oov means if new sentence word not present in vocab then change that to notheing word

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
tokenizer.word_index #for getting index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [ ]:
tokenizer.word_counts #for getting counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [ ]:
tokenizer.document_count

10

In [ ]:
sequences = tokenizer.texts_to_sequences(docs) #for getting doc convert to number vector
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [ ]:
from keras.utils import pad_sequences

In [ ]:
sequences = pad_sequences(sequences,padding='post')

In [ ]:
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [ ]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [ ]:
(X_train,y_train),(X_test,y_test) = imdb.load_data() #this data is tokenized and also integer encoded

17464789/17464789 [==============================] - 0s 0us/step


In [ ]:
X_train.shape

(25000,)

In [ ]:
print(X_train[0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [ ]:
len(X_train[2])

141

In [ ]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50) #trimming the sentence to have 50 words

In [ ]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [ ]:
model = Sequential()

model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False)) #32 nodes in rnn layer and it has input shape 50,1 means 50 timestamps
#return seq false means we are not output the Ot that goes to next stage
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 30s 34ms/step - loss: 0.6948 - accuracy: 0.5063 - val_loss: 0.6985 - val_accuracy: 0.4973
Epoch 2/5
782/782 [==============================] - 27s 35ms/step - loss: 0.6933 - accuracy: 0.5072 - val_loss: 0.6967 - val_accuracy: 0.5043
Epoch 3/5
782/782 [==============================] - 27s 35ms/step - loss: 0.6931 - accuracy: 0.5101 - val_loss: 0.6961 - val_accuracy: 0.5023
Epoch 4/5
782/782 [==============================] - 34s 43ms/step - loss: 0.6930 - accuracy: 0.5075 - val_loss: 0.6939 - val_accuracy: 0.5034
Epoch 5/5
782/782 [==============================] - 28s 36ms/step - loss: 0.6928 - accuracy: 0.5092 - val_loss: 0.6944 - val_accuracy: 0.5019


In [ ]:
#embeddings

#it is dense in nature unlike integer encoding
#In natural language processing, word embedding is a term used for the representation of words for text analysis,
#typically in the form of a real-valued vector that encodes the meaning of the word such that the words that are
#closer in vector space are expected tobe similar in meaning

#it capture semantic meaning

#word2vec, glove. these are pretrained embeddings
#in deeplearning we can learn the embeddings by aadding embedding layer

# sentence should be integer encoded before giving to embedding layer


In [ ]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [ ]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
len(tokenizer.word_index)

17

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [ ]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [ ]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))
#17 is vocablory we have means unique words
# 2 means we want to represent every word with two numbers
#5 is notal number of words in sentence
model.summary()

#embedding is neural ntwrk having 17,2  nodes , each word with OHE goe to 17 nodes as vocab is 17

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 5, 2)              34        
                                                                 
Total params: 34 (136.00 Byte)
Trainable params: 34 (136.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile('adam','accuracy')

In [ ]:
pred = model.predict(sequences) #for every word we are getting 2 numbers
print(pred)

1/1 [==============================] - 0s 36ms/step
[[[-0.02552691  0.01667677]
  [-0.04753822  0.02231318]
  [ 0.00626294  0.03294669]
  [ 0.00626294  0.03294669]
  [ 0.00626294  0.03294669]]

 [[-0.04753822  0.02231318]
  [-0.04753822  0.02231318]
  [ 0.00626294  0.03294669]
  [ 0.00626294  0.03294669]
  [ 0.00626294  0.03294669]]

 [[ 0.04532286 -0.04854931]
  [ 0.04532286 -0.04854931]
  [ 0.02062464  0.0333829 ]
  [ 0.00626294  0.03294669]
  [ 0.00626294  0.03294669]]

 [[-0.04819229 -0.00099261]
  [ 0.01442767  0.04900901]
  [-0.04819229 -0.00099261]
  [-0.04753822  0.02231318]
  [-0.04819229 -0.00099261]]

 [[ 0.04064227  0.00047513]
  [-0.02525802  0.04112801]
  [-0.01700842 -0.02750677]
  [-0.04479822  0.04290498]
  [ 0.00626294  0.03294669]]

 [[ 0.00136644 -0.01031942]
  [ 0.00136644 -0.01031942]
  [ 0.00626294  0.03294669]
  [ 0.00626294  0.03294669]
  [ 0.00626294  0.03294669]]

 [[ 0.01558002  0.0327526 ]
  [ 0.01558002  0.0327526 ]
  [ 0.00626294  0.03294669]
  [ 0.006262

In [ ]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [ ]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [ ]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [ ]:
X_train.shape

(25000, 50)

In [ ]:
import numpy as np
np.max(X_train)

88585

In [ ]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [ ]:
model = Sequential()
model.add(Embedding(88585, 2, input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 50, 2)             177170    
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 178323 (696.57 KB)
Trainable params: 178323 (696.57 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 66s 81ms/step - loss: 0.5259 - acc: 0.7304 - val_loss: 0.4524 - val_acc: 0.7906
Epoch 2/5
782/782 [==============================] - 41s 53ms/step - loss: 0.3187 - acc: 0.8686 - val_loss: 0.4288 - val_acc: 0.8102
Epoch 3/5
782/782 [==============================] - 45s 57ms/step - loss: 0.2210 - acc: 0.9168 - val_loss: 0.4710 - val_acc: 0.7993
Epoch 4/5
782/782 [==============================] - 41s 52ms/step - loss: 0.1618 - acc: 0.9429 - val_loss: 0.5737 - val_acc: 0.7909
Epoch 5/5
782/782 [==============================] - 41s 53ms/step - loss: 0.1246 - acc: 0.9581 - val_loss: 0.5647 - val_acc: 0.7890
