In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
# Vocabulary size
voc_size=10000

In [10]:
#One Hot Representation
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[1564, 6242, 8368, 8044], [1564, 6242, 8368, 7805], [1564, 3878, 8368, 813], [8645, 5131, 7204, 6893, 2374], [8645, 5131, 7204, 6893, 4683], [8404, 1564, 8448, 8368, 449], [7836, 5641, 5033, 6893]]


In [11]:
#Word Embedding Represntation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [14]:
sent_length=8 #making all same size of 8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) #padding=pre beacuse adding 0's at front
print(embedded_docs)

[[   0    0    0    0 1564 6242 8368 8044]
 [   0    0    0    0 1564 6242 8368 7805]
 [   0    0    0    0 1564 3878 8368  813]
 [   0    0    0 8645 5131 7204 6893 2374]
 [   0    0    0 8645 5131 7204 6893 4683]
 [   0    0    0 8404 1564 8448 8368  449]
 [   0    0    0    0 7836 5641 5033 6893]]


In [15]:
dim=10 #no. of dimension or features to represent

In [16]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 43ms/step
[[[ 0.00271305 -0.03297041 -0.01429566 -0.03650024 -0.0128387
   -0.0118825   0.04461275 -0.00876213  0.04984036  0.03714131]
  [ 0.00271305 -0.03297041 -0.01429566 -0.03650024 -0.0128387
   -0.0118825   0.04461275 -0.00876213  0.04984036  0.03714131]
  [ 0.00271305 -0.03297041 -0.01429566 -0.03650024 -0.0128387
   -0.0118825   0.04461275 -0.00876213  0.04984036  0.03714131]
  [ 0.00271305 -0.03297041 -0.01429566 -0.03650024 -0.0128387
   -0.0118825   0.04461275 -0.00876213  0.04984036  0.03714131]
  [-0.02013799  0.04860163 -0.00708432 -0.04602294  0.03118167
   -0.04097348 -0.00613388 -0.01169387  0.01975871 -0.02943571]
  [ 0.01318565 -0.01353449  0.0462007  -0.02077436 -0.03407869
   -0.02191174  0.00355594  0.00878308 -0.01828848 -0.04247258]
  [-0.01000359 -0.02902426  0.03545997 -0.01346067  0.0233253
    0.03863985  0.00399722 -0.00816602 -0.02756915  0.0429478 ]
  [-0.04607854 -0.0276564  -0.02331888  0.02841419  0.0145792
  

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 1564, 6242, 8368, 8044], dtype=int32)

In [21]:
print(model.predict(embedded_docs)[0]) #we get vector for every word in the sentence and size of vector is 10 as we defined

1/1 [==============================] - 0s 11ms/step
[[ 0.00271305 -0.03297041 -0.01429566 -0.03650024 -0.0128387  -0.0118825
   0.04461275 -0.00876213  0.04984036  0.03714131]
 [ 0.00271305 -0.03297041 -0.01429566 -0.03650024 -0.0128387  -0.0118825
   0.04461275 -0.00876213  0.04984036  0.03714131]
 [ 0.00271305 -0.03297041 -0.01429566 -0.03650024 -0.0128387  -0.0118825
   0.04461275 -0.00876213  0.04984036  0.03714131]
 [ 0.00271305 -0.03297041 -0.01429566 -0.03650024 -0.0128387  -0.0118825
   0.04461275 -0.00876213  0.04984036  0.03714131]
 [-0.02013799  0.04860163 -0.00708432 -0.04602294  0.03118167 -0.04097348
  -0.00613388 -0.01169387  0.01975871 -0.02943571]
 [ 0.01318565 -0.01353449  0.0462007  -0.02077436 -0.03407869 -0.02191174
   0.00355594  0.00878308 -0.01828848 -0.04247258]
 [-0.01000359 -0.02902426  0.03545997 -0.01346067  0.0233253   0.03863985
   0.00399722 -0.00816602 -0.02756915  0.0429478 ]
 [-0.04607854 -0.0276564  -0.02331888  0.02841419  0.0145792  -0.04179647
  -